### ISSUE TITLE
Aeon M3 Better values for bonus objectives

### ISSUE THREAD

**Issue by speed2CZ** [FAForever/faf-coop-maps#307]
Current values are too high
https://github.com/FAForever/faf-coop-maps/blob/master/SCCA_Coop_A03/SCCA_Coop_A03_script.lua#L284-L341

**Comment by Oxideion** [comment]
Regarding the static defenses: T2 turrets will be considered by the player to be far superior (AoE against air, AoE against drops, and the range helps with not knowing the drop points) so even something manageable, like 75 static defenses, will be hard to achieve. If it's possible, perhaps t2 turrets should count for three (or some other desired number) instead of one. 

Regarding the gunship goal: Absolutely ludicrous. With all the flak and cruisers gunships will be next to useless even in somewhat big numbers and making over a hundred gunships seems dumb when those resources could be invested into destroyers that can obliterate the entire map while gunships kill one base. 
Suggestions: Lower the number to something manageable (≤100, we are talking about T2 air units after all), switch it from gunships to torpedo bombers->far more useful, especially early on. 

Killing Arnold's destroyers: A reasonable objective. AI doesn't get the chance to build 50 destroyers on hard if the player is somewhat competent. Needs finetuning.
