### ISSUE TITLE
Cybran 6 buglist

### ISSUE THREAD

**Issue by MattDeering** [FAForever/faf-coop-maps#36]
We let the CZAR take off but killed it before it destroyed black sun. Next objective didn't spawn.
Continued on to kill the aeon acu and got a desync
Walls

Logs
https://gist.github.com/MattDeering/dfc86ac4b2bedbbd13fb
https://gist.github.com/MattDeering/fa1d403f3ce8dc66d0e1

theeggrolls
https://gist.github.com/theeggroll/096ff9973b73a9e9a5ea
https://gist.github.com/theeggroll/e5067ea3656ba01c746c

**Comment by theeggroll** [comment]
Also Base layout is inaccurate to original 
![image](https://cloud.githubusercontent.com/assets/10272223/8974833/23cba6fc-363c-11e5-89f5-c8e11f20b0f5.png)

**Comment by speed2CZ** [comment]
Map not expanding should be fixed with by this #28
I dont really see what's so inaccurate in base design, this is base for easiest difficulty:
![vystrizek](https://cloud.githubusercontent.com/assets/10947024/8984277/def66572-36d0-11e5-82f7-8591c054dedb.PNG)
Looks fine for me, can you be more specific?

**Comment by MattDeering** [comment]
We had only one of each factory at the start. It was on hard. Maybe in vanilla eggroll did it on medium.

**Comment by speed2CZ** [comment]
yes, hard = one of each factory, so that one is fixed too :D
